#!/bin/sh

if [ -z "$ISGUI" ]
then
	HTTP="links"
	VIDEO="mpv"
	AUDIO="mpv"
	GOPHER="lynx"
	IMAGE="sxiv"
	URL_IMAGE="feh"
	BOOKS="zathura"
	MULTIEMU="mednafen"
	NES="mesen"
	SNES="bsnes"
else
	HTTP="st -e links"
	VIDEO="mpv"
	AUDIO="st -e mpv"
	GOPHER="st -e lynx"
	IMAGE="sxiv"
	URL_IMAGE="feh"
	BOOKS="zathura"
	MULTIEMU="mednafen"
	NES="mesen"
	SNES="bsnes"
fi

COMIC=$BOOKS
PDF=$BOOKS
EPUB=$BOOKS
DJVU=$BOOKS

if [ -z "$FILE" ]
then
	if [ -z "$1" ]
	then
		return 0
	else
		FILE=$1
	fi
fi

case $(echo "$FILE" | tr '[:upper:]' '[:lower:]') in
*.epub) $EPUB "$FILE";;
*.pdf) $PDF "$FILE";;
*.cb[zr] | *.cb) $COMIC "$FILE";;
*.djvu) $DJVU "$FILE";;
*.mkv | *.mp4 | *.m4v) $VIDEO "$FILE";;
*.mp3 | *.flac) $AUDIO "$FILE";;
https://*.png | https://*.jpg | http://*.png | http://*.jpg) $URL_IMAGE "$FILE";;
*.png | *.jpg) $IMAGE "$FILE";;
*.nes) $NES "$FILE";;
*.sfc) $SNES "$FILE";;
*youtube.com/watch* | *yewtu.be/watch* | *youtu.be*) $VIDEO "$FILE";;
*youtube.com*) $HTTP "$(echo "$FILE" | sed -e 's/youtube.com/yewtu.be/g')";;
*twitter.com/*) $HTTP "$(echo "$FILE" | sed -e 's/twitter.com/nitter.net/g')";;
https://* | http://* | *.htm | *.html) $HTTP "$FILE";;
gopher://*) $GOPHER "$FILE";;
*) herbe "$FILE";;
esac