#!/bin/sh

case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
*.epub | *.pdf | *.cb[zr] | *.djvu) zathura "$1";;
*.mkv | *.mp4 | *.m4v | *.mp3 | *.flac) mpv "$1";;
https://*.png | https://*.jpg) feh "$1";;
*.png | *.jpg) sxiv "$1";;
*.nes) mesen "$1";;
*.sfc) bsnes "$1";;
*youtube.com/watch* | *yewtu.be/watch* | *youtu.be*) mpv "$1";;
*youtube.com*) links $(echo "$1" | sed -e 's/youtube.com/yewtu.be/g');;
https://* | *.htm | *.html) links "$1";;
*) vis "$1";;
esac